/**
 *
 * Autogenerated file. Do not modify.
 *
 * Generated by:
 *      ./gateway-config2cpp -h /home/andrei/src/rak_common_for_gateway/lora/rak2287/global_conf_usb/global_conf.as_915_921.json /home/andrei/src/rak_common_for_gateway/lora/rak2287/global_conf_usb/global_conf.as_915_928.json /home/andrei/src/rak_common_for_gateway/lora/rak2287/global_conf_usb/global_conf.as_917_920.json /home/andrei/src/rak_common_for_gateway/lora/rak2287/global_conf_usb/global_conf.as_920_923.json /home/andrei/src/rak_common_for_gateway/lora/rak2287/global_conf_usb/global_conf.au_915_928.json /home/andrei/src/rak_common_for_gateway/lora/rak2287/global_conf_usb/global_conf.cn_470_510.json /home/andrei/src/rak_common_for_gateway/lora/rak2287/global_conf_usb/global_conf.eu_433.json /home/andrei/src/rak_common_for_gateway/lora/rak2287/global_conf_usb/global_conf.eu_863_870.json /home/andrei/src/rak_common_for_gateway/lora/rak2287/global_conf_usb/global_conf.in_865_867.json /home/andrei/src/rak_common_for_gateway/lora/rak2287/global_conf_usb/global_conf.kr_920_923.json /home/andrei/src/rak_common_for_gateway/lora/rak2287/global_conf_usb/global_conf.ru_864_870.json /home/andrei/src/rak_common_for_gateway/lora/rak2287/global_conf_usb/global_conf.us_902_928.json 
 *
 */

#include "gateway-settings.h"

GatewaySettings lorawanGatewaySettings[] = {

{
	// as_915_921.sx1261
		.sx1261 = {
			.sx1261 = {
				.spi_path = "",
				.rssi_offset = 0
			},
			.spectralScan = {
				.enable = false,
				.freq_hz_start = 0,
				.nb_chan = 0,
				.nb_scan = 0,
				.pace_s = 0
			},
			.lbt = {
				.enable = false,
				.nb_channel = 0
			}
		},
		.sx130x = {
			.boardConf = {
				.lorawan_public = true,
				.clksrc = 0,
				.full_duplex = false,
				.com_type = (lgw_com_type_t) 1,
				.com_path = "/dev/ttyACM0"
			},
			.antennaGain = 0,
			.tsConf = {
				.enable = false,
				.mode = (lgw_ftime_mode_t) 0
			},
			.rfConfs = {
				// Radio 0
				{
					.enable = true,
					.freq_hz = 917000000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = true,
					.single_input_mode = false
				},
				// Radio 1
				{
					.enable = true,
					.freq_hz = 917800000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = false,
					.single_input_mode = false
				}
			},
			.tx_freq_min = {
				915000000,
				0
			},
			.tx_freq_max = {
				921000000,
				0
			},
			.txLut = {
				{
					.lut = {
						// TX LUT radio 0, count: 16
						{
								.rf_power = 12,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 6
						},
						{
								.rf_power = 13,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 7
						},
						{
								.rf_power = 14,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 8
						},
						{
								.rf_power = 15,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 9
						},
						{
								.rf_power = 16,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 10
						},
						{
								.rf_power = 17,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 11
						},
						{
								.rf_power = 18,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 12
						},
						{
								.rf_power = 19,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 13
						},
						{
								.rf_power = 20,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 14
						},
						{
								.rf_power = 21,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 15
						},
						{
								.rf_power = 22,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 16
						},
						{
								.rf_power = 23,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 17
						},
						{
								.rf_power = 24,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 18
						},
						{
								.rf_power = 25,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 19
						},
						{
								.rf_power = 26,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 21
						},
						{
								.rf_power = 27,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 22
						}
					},
					.size = 16
				},
				{
					.size = 0
				}
			},
			.ifConfs = {
				{
					// chan_multiSF_0
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_1
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_2
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 0
				},
				{
					// chan_multiSF_3
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 200000
				},
				{
					// chan_multiSF_4
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_5
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_6
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 0
				},
				{
					// chan_multiSF_7
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 200000
				}
			},
			// Lora std 
			.ifStdConf = {
				.enable = true,
				.rf_chain = 1,
				.freq_hz = 100000,
				.bandwidth = 5,
				.datarate = 7,
				.implicit_hdr = false,
				.implicit_payload_length = 17,
				.implicit_crc_en = false,
				.implicit_coderate = 1
			},
			// FSK 
			.ifFSKConf = {
				.enable = true,
				.rf_chain = 1,
				.freq_hz = 400000,
				.bandwidth = 4,
				.datarate = 50000
			},
			.demodConf = {
				// chan_multiSF_All spreading_factor_enable bit field
				.multisf_datarate = 0xff
			}
		},
	.gateway = {
		.gatewayId = 0xaa555a0000000000,
		.serverPortUp = 1700,
		.serverPortDown = 1700,
		.keepaliveInterval = 10,
		.statInterval = 30,
		.pushTimeoutMs = {
			.tv_sec = 0,
			.tv_usec = 50000
		},
		.forwardCRCValid = true,
		.forwardCRCError = false,
		.forwardCRCDisabled = false,
		.refGeoCoordinates = {
			.lat = 0,
			.lon = 0,
			.alt = 0
		},
		.fakeGPS = false,
		.beaconPeriod = 0,
		.beaconFreqHz = 916800000,
		.beaconFreqNb = 1,
		.beaconFreqStep = 0,
		.beaconDataRate = 9,
		.beaconBandwidthHz = 125000,
		.beaconInfoDesc = 0,
		.autoQuitThreshold = 0
	},
	// Debug nb_ref_payload, count: 2
	.debug = {
		.nb_ref_payload = 2,
		.ref_payload = {
			{
				.id = 0xcafe1234
			},
			{
				.id = 0xcafe2345
			}
		},
		.log_file_name = "loragw_hal.log"
	},
	.serverAddr = "eu1.cloud.thethings.network",
	.gpsTtyPath = "/dev/ttyAMA0",
	.name = "AS-915-921",
},
{
	// as_915_928.sx1261
		.sx1261 = {
			.sx1261 = {
				.spi_path = "",
				.rssi_offset = 0
			},
			.spectralScan = {
				.enable = false,
				.freq_hz_start = 0,
				.nb_chan = 0,
				.nb_scan = 0,
				.pace_s = 0
			},
			.lbt = {
				.enable = false,
				.nb_channel = 0
			}
		},
		.sx130x = {
			.boardConf = {
				.lorawan_public = true,
				.clksrc = 0,
				.full_duplex = false,
				.com_type = (lgw_com_type_t) 1,
				.com_path = "/dev/ttyACM0"
			},
			.antennaGain = 0,
			.tsConf = {
				.enable = false,
				.mode = (lgw_ftime_mode_t) 0
			},
			.rfConfs = {
				// Radio 0
				{
					.enable = true,
					.freq_hz = 923600000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = true,
					.single_input_mode = false
				},
				// Radio 1
				{
					.enable = true,
					.freq_hz = 924400000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = false,
					.single_input_mode = false
				}
			},
			.tx_freq_min = {
				915000000,
				0
			},
			.tx_freq_max = {
				928000000,
				0
			},
			.txLut = {
				{
					.lut = {
						// TX LUT radio 0, count: 16
						{
								.rf_power = 12,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 6
						},
						{
								.rf_power = 13,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 7
						},
						{
								.rf_power = 14,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 8
						},
						{
								.rf_power = 15,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 9
						},
						{
								.rf_power = 16,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 10
						},
						{
								.rf_power = 17,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 11
						},
						{
								.rf_power = 18,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 12
						},
						{
								.rf_power = 19,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 13
						},
						{
								.rf_power = 20,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 14
						},
						{
								.rf_power = 21,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 15
						},
						{
								.rf_power = 22,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 16
						},
						{
								.rf_power = 23,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 17
						},
						{
								.rf_power = 24,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 18
						},
						{
								.rf_power = 25,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 19
						},
						{
								.rf_power = 26,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 21
						},
						{
								.rf_power = 27,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 22
						}
					},
					.size = 16
				},
				{
					.size = 0
				}
			},
			.ifConfs = {
				{
					// chan_multiSF_0
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_1
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_2
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 0
				},
				{
					// chan_multiSF_3
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 200000
				},
				{
					// chan_multiSF_4
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_5
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_6
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 0
				},
				{
					// chan_multiSF_7
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 200000
				}
			},
			// Lora std 
			.ifStdConf = {
				.enable = true,
				.rf_chain = 1,
				.freq_hz = 100000,
				.bandwidth = 5,
				.datarate = 7,
				.implicit_hdr = false,
				.implicit_payload_length = 17,
				.implicit_crc_en = false,
				.implicit_coderate = 1
			},
			// FSK 
			.ifFSKConf = {
				.enable = true,
				.rf_chain = 1,
				.freq_hz = 400000,
				.bandwidth = 4,
				.datarate = 50000
			},
			.demodConf = {
				// chan_multiSF_All spreading_factor_enable bit field
				.multisf_datarate = 0xff
			}
		},
	.gateway = {
		.gatewayId = 0xaa555a0000000000,
		.serverPortUp = 1700,
		.serverPortDown = 1700,
		.keepaliveInterval = 10,
		.statInterval = 30,
		.pushTimeoutMs = {
			.tv_sec = 0,
			.tv_usec = 50000
		},
		.forwardCRCValid = true,
		.forwardCRCError = false,
		.forwardCRCDisabled = false,
		.refGeoCoordinates = {
			.lat = 0,
			.lon = 0,
			.alt = 0
		},
		.fakeGPS = false,
		.beaconPeriod = 0,
		.beaconFreqHz = 923400000,
		.beaconFreqNb = 1,
		.beaconFreqStep = 0,
		.beaconDataRate = 9,
		.beaconBandwidthHz = 125000,
		.beaconInfoDesc = 0,
		.autoQuitThreshold = 0
	},
	// Debug nb_ref_payload, count: 2
	.debug = {
		.nb_ref_payload = 2,
		.ref_payload = {
			{
				.id = 0xcafe1234
			},
			{
				.id = 0xcafe2345
			}
		},
		.log_file_name = "loragw_hal.log"
	},
	.serverAddr = "eu1.cloud.thethings.network",
	.gpsTtyPath = "/dev/ttyAMA0",
	.name = "AS-915-928",
},
{
	// as_917_920.sx1261
		.sx1261 = {
			.sx1261 = {
				.spi_path = "",
				.rssi_offset = 0
			},
			.spectralScan = {
				.enable = false,
				.freq_hz_start = 0,
				.nb_chan = 0,
				.nb_scan = 0,
				.pace_s = 0
			},
			.lbt = {
				.enable = false,
				.nb_channel = 0
			}
		},
		.sx130x = {
			.boardConf = {
				.lorawan_public = true,
				.clksrc = 0,
				.full_duplex = false,
				.com_type = (lgw_com_type_t) 1,
				.com_path = "/dev/ttyACM0"
			},
			.antennaGain = 0,
			.tsConf = {
				.enable = false,
				.mode = (lgw_ftime_mode_t) 0
			},
			.rfConfs = {
				// Radio 0
				{
					.enable = true,
					.freq_hz = 917700000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = true,
					.single_input_mode = false
				},
				// Radio 1
				{
					.enable = true,
					.freq_hz = 918500000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = false,
					.single_input_mode = false
				}
			},
			.tx_freq_min = {
				917000000,
				0
			},
			.tx_freq_max = {
				920000000,
				0
			},
			.txLut = {
				{
					.lut = {
						// TX LUT radio 0, count: 16
						{
								.rf_power = 12,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 6
						},
						{
								.rf_power = 13,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 7
						},
						{
								.rf_power = 14,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 8
						},
						{
								.rf_power = 15,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 9
						},
						{
								.rf_power = 16,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 10
						},
						{
								.rf_power = 17,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 11
						},
						{
								.rf_power = 18,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 12
						},
						{
								.rf_power = 19,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 13
						},
						{
								.rf_power = 20,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 14
						},
						{
								.rf_power = 21,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 15
						},
						{
								.rf_power = 22,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 16
						},
						{
								.rf_power = 23,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 17
						},
						{
								.rf_power = 24,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 18
						},
						{
								.rf_power = 25,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 19
						},
						{
								.rf_power = 26,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 21
						},
						{
								.rf_power = 27,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 22
						}
					},
					.size = 16
				},
				{
					.size = 0
				}
			},
			.ifConfs = {
				{
					// chan_multiSF_0
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_1
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_2
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 0
				},
				{
					// chan_multiSF_3
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 200000
				},
				{
					// chan_multiSF_4
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_5
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_6
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 0
				},
				{
					// chan_multiSF_7
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 200000
				}
			},
			// Lora std 
			.ifStdConf = {
				.enable = true,
				.rf_chain = 1,
				.freq_hz = 100000,
				.bandwidth = 5,
				.datarate = 7,
				.implicit_hdr = false,
				.implicit_payload_length = 17,
				.implicit_crc_en = false,
				.implicit_coderate = 1
			},
			// FSK 
			.ifFSKConf = {
				.enable = true,
				.rf_chain = 1,
				.freq_hz = 400000,
				.bandwidth = 4,
				.datarate = 50000
			},
			.demodConf = {
				// chan_multiSF_All spreading_factor_enable bit field
				.multisf_datarate = 0xff
			}
		},
	.gateway = {
		.gatewayId = 0xaa555a0000000000,
		.serverPortUp = 1700,
		.serverPortDown = 1700,
		.keepaliveInterval = 10,
		.statInterval = 30,
		.pushTimeoutMs = {
			.tv_sec = 0,
			.tv_usec = 50000
		},
		.forwardCRCValid = true,
		.forwardCRCError = false,
		.forwardCRCDisabled = false,
		.refGeoCoordinates = {
			.lat = 0,
			.lon = 0,
			.alt = 0
		},
		.fakeGPS = false,
		.beaconPeriod = 0,
		.beaconFreqHz = 917500000,
		.beaconFreqNb = 1,
		.beaconFreqStep = 0,
		.beaconDataRate = 9,
		.beaconBandwidthHz = 125000,
		.beaconInfoDesc = 0,
		.autoQuitThreshold = 0
	},
	// Debug nb_ref_payload, count: 2
	.debug = {
		.nb_ref_payload = 2,
		.ref_payload = {
			{
				.id = 0xcafe1234
			},
			{
				.id = 0xcafe2345
			}
		},
		.log_file_name = "loragw_hal.log"
	},
	.serverAddr = "eu1.cloud.thethings.network",
	.gpsTtyPath = "/dev/ttyAMA0",
	.name = "AS-917-920",
},
{
	// as_920_923.sx1261
		.sx1261 = {
			.sx1261 = {
				.spi_path = "",
				.rssi_offset = 0
			},
			.spectralScan = {
				.enable = false,
				.freq_hz_start = 0,
				.nb_chan = 0,
				.nb_scan = 0,
				.pace_s = 0
			},
			.lbt = {
				.enable = false,
				.nb_channel = 0
			}
		},
		.sx130x = {
			.boardConf = {
				.lorawan_public = true,
				.clksrc = 0,
				.full_duplex = false,
				.com_type = (lgw_com_type_t) 1,
				.com_path = "/dev/ttyACM0"
			},
			.antennaGain = 0,
			.tsConf = {
				.enable = false,
				.mode = (lgw_ftime_mode_t) 0
			},
			.rfConfs = {
				// Radio 0
				{
					.enable = true,
					.freq_hz = 921800000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = true,
					.single_input_mode = false
				},
				// Radio 1
				{
					.enable = true,
					.freq_hz = 922600000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = false,
					.single_input_mode = false
				}
			},
			.tx_freq_min = {
				920000000,
				0
			},
			.tx_freq_max = {
				923000000,
				0
			},
			.txLut = {
				{
					.lut = {
						// TX LUT radio 0, count: 16
						{
								.rf_power = 12,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 1
						},
						{
								.rf_power = 13,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 2
						},
						{
								.rf_power = 14,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 3
						},
						{
								.rf_power = 15,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 4
						},
						{
								.rf_power = 16,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 5
						},
						{
								.rf_power = 17,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 6
						},
						{
								.rf_power = 18,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 8
						},
						{
								.rf_power = 19,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 13
						},
						{
								.rf_power = 20,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 10
						},
						{
								.rf_power = 21,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 15
						},
						{
								.rf_power = 22,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 12
						},
						{
								.rf_power = 23,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 13
						},
						{
								.rf_power = 24,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 14
						},
						{
								.rf_power = 25,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 16
						},
						{
								.rf_power = 26,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 17
						},
						{
								.rf_power = 27,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 19
						}
					},
					.size = 16
				},
				{
					.size = 0
				}
			},
			.ifConfs = {
				{
					// chan_multiSF_0
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_1
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_2
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 0
				},
				{
					// chan_multiSF_3
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 200000
				},
				{
					// chan_multiSF_4
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_5
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_6
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 0
				},
				{
					// chan_multiSF_7
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 200000
				}
			},
			// Lora std 
			.ifStdConf = {
				.enable = true,
				.rf_chain = 1,
				.freq_hz = 100000,
				.bandwidth = 5,
				.datarate = 7,
				.implicit_hdr = false,
				.implicit_payload_length = 17,
				.implicit_crc_en = false,
				.implicit_coderate = 1
			},
			// FSK 
			.ifFSKConf = {
				.enable = true,
				.rf_chain = 1,
				.freq_hz = 400000,
				.bandwidth = 4,
				.datarate = 50000
			},
			.demodConf = {
				// chan_multiSF_All spreading_factor_enable bit field
				.multisf_datarate = 0xff
			}
		},
	.gateway = {
		.gatewayId = 0xaa555a0000000000,
		.serverPortUp = 1700,
		.serverPortDown = 1700,
		.keepaliveInterval = 10,
		.statInterval = 30,
		.pushTimeoutMs = {
			.tv_sec = 0,
			.tv_usec = 50000
		},
		.forwardCRCValid = true,
		.forwardCRCError = false,
		.forwardCRCDisabled = false,
		.refGeoCoordinates = {
			.lat = 0,
			.lon = 0,
			.alt = 0
		},
		.fakeGPS = false,
		.beaconPeriod = 0,
		.beaconFreqHz = 921600000,
		.beaconFreqNb = 1,
		.beaconFreqStep = 0,
		.beaconDataRate = 9,
		.beaconBandwidthHz = 125000,
		.beaconInfoDesc = 0,
		.autoQuitThreshold = 0
	},
	// Debug nb_ref_payload, count: 2
	.debug = {
		.nb_ref_payload = 2,
		.ref_payload = {
			{
				.id = 0xcafe1234
			},
			{
				.id = 0xcafe2345
			}
		},
		.log_file_name = "loragw_hal.log"
	},
	.serverAddr = "eu1.cloud.thethings.network",
	.gpsTtyPath = "/dev/ttyAMA0",
	.name = "AS-920-923",
},
{
	// au_915_928.sx1261
		.sx1261 = {
			.sx1261 = {
				.spi_path = "",
				.rssi_offset = 0
			},
			.spectralScan = {
				.enable = false,
				.freq_hz_start = 0,
				.nb_chan = 0,
				.nb_scan = 0,
				.pace_s = 0
			},
			.lbt = {
				.enable = false,
				.nb_channel = 0
			}
		},
		.sx130x = {
			.boardConf = {
				.lorawan_public = true,
				.clksrc = 0,
				.full_duplex = false,
				.com_type = (lgw_com_type_t) 1,
				.com_path = "/dev/ttyACM0"
			},
			.antennaGain = 0,
			.tsConf = {
				.enable = false,
				.mode = (lgw_ftime_mode_t) 0
			},
			.rfConfs = {
				// Radio 0
				{
					.enable = true,
					.freq_hz = 917200000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = true,
					.single_input_mode = false
				},
				// Radio 1
				{
					.enable = true,
					.freq_hz = 917900000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = false,
					.single_input_mode = false
				}
			},
			.tx_freq_min = {
				915000000,
				0
			},
			.tx_freq_max = {
				928000000,
				0
			},
			.txLut = {
				{
					.lut = {
						// TX LUT radio 0, count: 16
						{
								.rf_power = 12,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 6
						},
						{
								.rf_power = 13,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 7
						},
						{
								.rf_power = 14,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 8
						},
						{
								.rf_power = 15,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 9
						},
						{
								.rf_power = 16,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 10
						},
						{
								.rf_power = 17,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 11
						},
						{
								.rf_power = 18,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 12
						},
						{
								.rf_power = 19,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 13
						},
						{
								.rf_power = 20,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 14
						},
						{
								.rf_power = 21,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 15
						},
						{
								.rf_power = 22,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 16
						},
						{
								.rf_power = 23,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 17
						},
						{
								.rf_power = 24,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 18
						},
						{
								.rf_power = 25,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 19
						},
						{
								.rf_power = 26,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 21
						},
						{
								.rf_power = 27,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 22
						}
					},
					.size = 16
				},
				{
					.size = 0
				}
			},
			.ifConfs = {
				{
					// chan_multiSF_0
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_1
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_2
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 0
				},
				{
					// chan_multiSF_3
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 200000
				},
				{
					// chan_multiSF_4
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -300000
				},
				{
					// chan_multiSF_5
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -100000
				},
				{
					// chan_multiSF_6
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 100000
				},
				{
					// chan_multiSF_7
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 300000
				}
			},
			// Lora std 
			.ifStdConf = {
				.enable = true,
				.rf_chain = 0,
				.freq_hz = 300000,
				.bandwidth = 6,
				.datarate = 8,
				.implicit_hdr = false,
				.implicit_payload_length = 17,
				.implicit_crc_en = false,
				.implicit_coderate = 1
			},
			// FSK 
			.ifFSKConf = {
				.enable = false,
				.rf_chain = 1,
				.freq_hz = 300000,
				.bandwidth = 4,
				.datarate = 50000
			},
			.demodConf = {
				// chan_multiSF_All spreading_factor_enable bit field
				.multisf_datarate = 0xff
			}
		},
	.gateway = {
		.gatewayId = 0xaa555a0000000000,
		.serverPortUp = 1700,
		.serverPortDown = 1700,
		.keepaliveInterval = 10,
		.statInterval = 30,
		.pushTimeoutMs = {
			.tv_sec = 0,
			.tv_usec = 50000
		},
		.forwardCRCValid = true,
		.forwardCRCError = false,
		.forwardCRCDisabled = false,
		.refGeoCoordinates = {
			.lat = 0,
			.lon = 0,
			.alt = 0
		},
		.fakeGPS = false,
		.beaconPeriod = 0,
		.beaconFreqHz = 923300000,
		.beaconFreqNb = 8,
		.beaconFreqStep = 600000,
		.beaconDataRate = 12,
		.beaconBandwidthHz = 500000,
		.beaconInfoDesc = 0,
		.autoQuitThreshold = 0
	},
	// Debug nb_ref_payload, count: 2
	.debug = {
		.nb_ref_payload = 2,
		.ref_payload = {
			{
				.id = 0xcafe1234
			},
			{
				.id = 0xcafe2345
			}
		},
		.log_file_name = "loragw_hal.log"
	},
	.serverAddr = "au1.cloud.thethings.network",
	.gpsTtyPath = "/dev/ttyAMA0",
	.name = "AU-915-928",
},
{
	// cn_470_510.sx1261
		.sx1261 = {
			.sx1261 = {
				.spi_path = "",
				.rssi_offset = 0
			},
			.spectralScan = {
				.enable = false,
				.freq_hz_start = 0,
				.nb_chan = 0,
				.nb_scan = 0,
				.pace_s = 0
			},
			.lbt = {
				.enable = false,
				.nb_channel = 0
			}
		},
		.sx130x = {
			.boardConf = {
				.lorawan_public = true,
				.clksrc = 0,
				.full_duplex = false,
				.com_type = (lgw_com_type_t) 1,
				.com_path = "/dev/ttyACM0"
			},
			.antennaGain = 0,
			.tsConf = {
				.enable = false,
				.mode = (lgw_ftime_mode_t) 0
			},
			.rfConfs = {
				// Radio 0
				{
					.enable = true,
					.freq_hz = 486600000,
					.rssi_offset = -207,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = true,
					.single_input_mode = true
				},
				// Radio 1
				{
					.enable = true,
					.freq_hz = 487400000,
					.rssi_offset = -207,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = false,
					.single_input_mode = true
				}
			},
			.tx_freq_min = {
				470000000,
				0
			},
			.tx_freq_max = {
				510000000,
				0
			},
			.txLut = {
				{
					.lut = {
						// TX LUT radio 0, count: 16
						{
								.rf_power = -6,
								.dig_gain = 0,
								.pa_gain = 0,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 0
						},
						{
								.rf_power = -3,
								.dig_gain = 0,
								.pa_gain = 0,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 1
						},
						{
								.rf_power = 0,
								.dig_gain = 0,
								.pa_gain = 0,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 2
						},
						{
								.rf_power = 3,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 3
						},
						{
								.rf_power = 6,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 4
						},
						{
								.rf_power = 10,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 5
						},
						{
								.rf_power = 11,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 6
						},
						{
								.rf_power = 12,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 7
						},
						{
								.rf_power = 13,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 8
						},
						{
								.rf_power = 14,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 9
						},
						{
								.rf_power = 16,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 10
						},
						{
								.rf_power = 20,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 11
						},
						{
								.rf_power = 23,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 12
						},
						{
								.rf_power = 25,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 13
						},
						{
								.rf_power = 26,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 14
						},
						{
								.rf_power = 27,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 15
						}
					},
					.size = 16
				},
				{
					.size = 0
				}
			},
			.ifConfs = {
				{
					// chan_multiSF_0
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -300000
				},
				{
					// chan_multiSF_1
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -100000
				},
				{
					// chan_multiSF_2
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 100000
				},
				{
					// chan_multiSF_3
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 300000
				},
				{
					// chan_multiSF_4
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -300000
				},
				{
					// chan_multiSF_5
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -100000
				},
				{
					// chan_multiSF_6
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 100000
				},
				{
					// chan_multiSF_7
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 300000
				}
			},
			// Lora std 
			.ifStdConf = {
				.enable = false,
				.rf_chain = 1,
				.freq_hz = -200000,
				.bandwidth = 5,
				.datarate = 7,
				.implicit_hdr = false,
				.implicit_payload_length = 17,
				.implicit_crc_en = false,
				.implicit_coderate = 1
			},
			// FSK 
			.ifFSKConf = {
				.enable = false,
				.rf_chain = 1,
				.freq_hz = 300000,
				.bandwidth = 4,
				.datarate = 50000
			},
			.demodConf = {
				// chan_multiSF_All spreading_factor_enable bit field
				.multisf_datarate = 0xff
			}
		},
	.gateway = {
		.gatewayId = 0x0,
		.serverPortUp = 1700,
		.serverPortDown = 1700,
		.keepaliveInterval = 10,
		.statInterval = 30,
		.pushTimeoutMs = {
			.tv_sec = 0,
			.tv_usec = 50000
		},
		.forwardCRCValid = true,
		.forwardCRCError = false,
		.forwardCRCDisabled = false,
		.refGeoCoordinates = {
			.lat = 0,
			.lon = 0,
			.alt = 0
		},
		.fakeGPS = false,
		.beaconPeriod = 0,
		.beaconFreqHz = 508300000,
		.beaconFreqNb = 8,
		.beaconFreqStep = 200000,
		.beaconDataRate = 10,
		.beaconBandwidthHz = 125000,
		.beaconInfoDesc = 0,
		.autoQuitThreshold = 20
	},
	// Debug nb_ref_payload, count: 2
	.debug = {
		.nb_ref_payload = 2,
		.ref_payload = {
			{
				.id = 0xcafe1234
			},
			{
				.id = 0xcafe2345
			}
		},
		.log_file_name = "loragw_hal.log"
	},
	.serverAddr = "au1.cloud.thethings.network",
	.gpsTtyPath = "/dev/ttyAMA0",
	.name = "CN-470-510",
},
{
	// eu_433.sx1261
		.sx1261 = {
			.sx1261 = {
				.spi_path = "",
				.rssi_offset = 0
			},
			.spectralScan = {
				.enable = false,
				.freq_hz_start = 0,
				.nb_chan = 0,
				.nb_scan = 0,
				.pace_s = 0
			},
			.lbt = {
				.enable = false,
				.nb_channel = 0
			}
		},
		.sx130x = {
			.boardConf = {
				.lorawan_public = true,
				.clksrc = 0,
				.full_duplex = false,
				.com_type = (lgw_com_type_t) 1,
				.com_path = "/dev/ttyACM0"
			},
			.antennaGain = 0,
			.tsConf = {
				.enable = false,
				.mode = (lgw_ftime_mode_t) 0
			},
			.rfConfs = {
				// Radio 0
				{
					.enable = true,
					.freq_hz = 434375000,
					.rssi_offset = -207,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = true,
					.single_input_mode = true
				},
				// Radio 1
				{
					.enable = true,
					.freq_hz = 433575000,
					.rssi_offset = -207,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = false,
					.single_input_mode = true
				}
			},
			.tx_freq_min = {
				433050000,
				0
			},
			.tx_freq_max = {
				434900000,
				0
			},
			.txLut = {
				{
					.lut = {
						// TX LUT radio 0, count: 16
						{
								.rf_power = -6,
								.dig_gain = 0,
								.pa_gain = 0,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 0
						},
						{
								.rf_power = -3,
								.dig_gain = 0,
								.pa_gain = 0,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 1
						},
						{
								.rf_power = 0,
								.dig_gain = 0,
								.pa_gain = 0,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 2
						},
						{
								.rf_power = 3,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 3
						},
						{
								.rf_power = 6,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 4
						},
						{
								.rf_power = 10,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 5
						},
						{
								.rf_power = 11,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 6
						},
						{
								.rf_power = 12,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 7
						},
						{
								.rf_power = 13,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 8
						},
						{
								.rf_power = 14,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 9
						},
						{
								.rf_power = 16,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 10
						},
						{
								.rf_power = 20,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 11
						},
						{
								.rf_power = 23,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 12
						},
						{
								.rf_power = 25,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 13
						},
						{
								.rf_power = 26,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 14
						},
						{
								.rf_power = 27,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 15
						}
					},
					.size = 16
				},
				{
					.size = 0
				}
			},
			.ifConfs = {
				{
					// chan_multiSF_0
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_1
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_2
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 0
				},
				{
					// chan_multiSF_3
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 200000
				},
				{
					// chan_multiSF_4
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_5
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_6
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 0
				},
				{
					// chan_multiSF_7
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 200000
				}
			},
			// Lora std 
			.ifStdConf = {
				.enable = true,
				.rf_chain = 1,
				.freq_hz = -200000,
				.bandwidth = 5,
				.datarate = 7,
				.implicit_hdr = false,
				.implicit_payload_length = 17,
				.implicit_crc_en = false,
				.implicit_coderate = 1
			},
			// FSK 
			.ifFSKConf = {
				.enable = true,
				.rf_chain = 1,
				.freq_hz = 300000,
				.bandwidth = 4,
				.datarate = 50000
			},
			.demodConf = {
				// chan_multiSF_All spreading_factor_enable bit field
				.multisf_datarate = 0xff
			}
		},
	.gateway = {
		.gatewayId = 0x0,
		.serverPortUp = 1700,
		.serverPortDown = 1700,
		.keepaliveInterval = 10,
		.statInterval = 30,
		.pushTimeoutMs = {
			.tv_sec = 0,
			.tv_usec = 50000
		},
		.forwardCRCValid = true,
		.forwardCRCError = false,
		.forwardCRCDisabled = false,
		.refGeoCoordinates = {
			.lat = 0,
			.lon = 0,
			.alt = 0
		},
		.fakeGPS = false,
		.beaconPeriod = 0,
		.beaconFreqHz = 434665000,
		.beaconFreqNb = 1,
		.beaconFreqStep = 0,
		.beaconDataRate = 9,
		.beaconBandwidthHz = 125000,
		.beaconInfoDesc = 0,
		.autoQuitThreshold = 20
	},
	// Debug nb_ref_payload, count: 2
	.debug = {
		.nb_ref_payload = 2,
		.ref_payload = {
			{
				.id = 0xcafe1234
			},
			{
				.id = 0xcafe2345
			}
		},
		.log_file_name = "loragw_hal.log"
	},
	.serverAddr = "eu1.cloud.thethings.network",
	.gpsTtyPath = "/dev/ttyAMA0",
	.name = "EU-433",
},
{
	// eu_863_870.sx1261
		.sx1261 = {
			.sx1261 = {
				.spi_path = "",
				.rssi_offset = 0
			},
			.spectralScan = {
				.enable = false,
				.freq_hz_start = 0,
				.nb_chan = 0,
				.nb_scan = 0,
				.pace_s = 0
			},
			.lbt = {
				.enable = false,
				.nb_channel = 0
			}
		},
		.sx130x = {
			.boardConf = {
				.lorawan_public = true,
				.clksrc = 0,
				.full_duplex = false,
				.com_type = (lgw_com_type_t) 1,
				.com_path = "/dev/ttyACM0"
			},
			.antennaGain = 0,
			.tsConf = {
				.enable = false,
				.mode = (lgw_ftime_mode_t) 0
			},
			.rfConfs = {
				// Radio 0
				{
					.enable = true,
					.freq_hz = 867500000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = true,
					.single_input_mode = false
				},
				// Radio 1
				{
					.enable = true,
					.freq_hz = 868500000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = false,
					.single_input_mode = false
				}
			},
			.tx_freq_min = {
				863000000,
				0
			},
			.tx_freq_max = {
				870000000,
				0
			},
			.txLut = {
				{
					.lut = {
						// TX LUT radio 0, count: 16
						{
								.rf_power = 12,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 4
						},
						{
								.rf_power = 13,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 5
						},
						{
								.rf_power = 14,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 6
						},
						{
								.rf_power = 15,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 7
						},
						{
								.rf_power = 16,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 8
						},
						{
								.rf_power = 17,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 9
						},
						{
								.rf_power = 18,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 10
						},
						{
								.rf_power = 19,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 11
						},
						{
								.rf_power = 20,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 12
						},
						{
								.rf_power = 21,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 13
						},
						{
								.rf_power = 22,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 14
						},
						{
								.rf_power = 23,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 16
						},
						{
								.rf_power = 24,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 17
						},
						{
								.rf_power = 25,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 18
						},
						{
								.rf_power = 26,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 19
						},
						{
								.rf_power = 27,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 22
						}
					},
					.size = 16
				},
				{
					.size = 0
				}
			},
			.ifConfs = {
				{
					// chan_multiSF_0
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_1
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_2
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 0
				},
				{
					// chan_multiSF_3
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_4
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_5
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 0
				},
				{
					// chan_multiSF_6
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 200000
				},
				{
					// chan_multiSF_7
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 400000
				}
			},
			// Lora std 
			.ifStdConf = {
				.enable = true,
				.rf_chain = 1,
				.freq_hz = -200000,
				.bandwidth = 5,
				.datarate = 7,
				.implicit_hdr = false,
				.implicit_payload_length = 17,
				.implicit_crc_en = false,
				.implicit_coderate = 1
			},
			// FSK 
			.ifFSKConf = {
				.enable = true,
				.rf_chain = 1,
				.freq_hz = 300000,
				.bandwidth = 4,
				.datarate = 50000
			},
			.demodConf = {
				// chan_multiSF_All spreading_factor_enable bit field
				.multisf_datarate = 0xff
			}
		},
	.gateway = {
		.gatewayId = 0xaa555a0000000000,
		.serverPortUp = 1700,
		.serverPortDown = 1700,
		.keepaliveInterval = 10,
		.statInterval = 30,
		.pushTimeoutMs = {
			.tv_sec = 0,
			.tv_usec = 50000
		},
		.forwardCRCValid = true,
		.forwardCRCError = false,
		.forwardCRCDisabled = false,
		.refGeoCoordinates = {
			.lat = 0,
			.lon = 0,
			.alt = 0
		},
		.fakeGPS = false,
		.beaconPeriod = 0,
		.beaconFreqHz = 869525000,
		.beaconFreqNb = 1,
		.beaconFreqStep = 0,
		.beaconDataRate = 9,
		.beaconBandwidthHz = 125000,
		.beaconInfoDesc = 0,
		.autoQuitThreshold = 0
	},
	// Debug nb_ref_payload, count: 2
	.debug = {
		.nb_ref_payload = 2,
		.ref_payload = {
			{
				.id = 0xcafe1234
			},
			{
				.id = 0xcafe2345
			}
		},
		.log_file_name = "loragw_hal.log"
	},
	.serverAddr = "eu1.cloud.thethings.network",
	.gpsTtyPath = "/dev/ttyAMA0",
	.name = "EU-863-870",
},
{
	// in_865_867.sx1261
		.sx1261 = {
			.sx1261 = {
				.spi_path = "",
				.rssi_offset = 0
			},
			.spectralScan = {
				.enable = false,
				.freq_hz_start = 0,
				.nb_chan = 0,
				.nb_scan = 0,
				.pace_s = 0
			},
			.lbt = {
				.enable = false,
				.nb_channel = 0
			}
		},
		.sx130x = {
			.boardConf = {
				.lorawan_public = true,
				.clksrc = 0,
				.full_duplex = false,
				.com_type = (lgw_com_type_t) 1,
				.com_path = "/dev/ttyACM0"
			},
			.antennaGain = 0,
			.tsConf = {
				.enable = false,
				.mode = (lgw_ftime_mode_t) 0
			},
			.rfConfs = {
				// Radio 0
				{
					.enable = true,
					.freq_hz = 865200000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = true,
					.single_input_mode = false
				},
				// Radio 1
				{
					.enable = true,
					.freq_hz = 866385000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = false,
					.single_input_mode = false
				}
			},
			.tx_freq_min = {
				865000000,
				0
			},
			.tx_freq_max = {
				867000000,
				0
			},
			.txLut = {
				{
					.lut = {
						// TX LUT radio 0, count: 16
						{
								.rf_power = 12,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 4
						},
						{
								.rf_power = 13,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 5
						},
						{
								.rf_power = 14,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 6
						},
						{
								.rf_power = 15,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 7
						},
						{
								.rf_power = 16,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 8
						},
						{
								.rf_power = 17,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 9
						},
						{
								.rf_power = 18,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 10
						},
						{
								.rf_power = 19,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 11
						},
						{
								.rf_power = 20,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 12
						},
						{
								.rf_power = 21,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 13
						},
						{
								.rf_power = 22,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 14
						},
						{
								.rf_power = 23,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 16
						},
						{
								.rf_power = 24,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 17
						},
						{
								.rf_power = 25,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 18
						},
						{
								.rf_power = 26,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 19
						},
						{
								.rf_power = 27,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 22
						}
					},
					.size = 16
				},
				{
					.size = 0
				}
			},
			.ifConfs = {
				{
					// chan_multiSF_0
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -137500
				},
				{
					// chan_multiSF_1
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 202500
				},
				{
					// chan_multiSF_2
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_3
					.enable = false,
					.rf_chain = 0,
					.freq_hz = 200000
				},
				{
					// chan_multiSF_4
					.enable = false,
					.rf_chain = 1,
					.freq_hz = -300000
				},
				{
					// chan_multiSF_5
					.enable = false,
					.rf_chain = 1,
					.freq_hz = -100000
				},
				{
					// chan_multiSF_6
					.enable = false,
					.rf_chain = 1,
					.freq_hz = 100000
				},
				{
					// chan_multiSF_7
					.enable = false,
					.rf_chain = 1,
					.freq_hz = 300000
				}
			},
			// Lora std 
			.ifStdConf = {
				.enable = false,
				.rf_chain = 0,
				.freq_hz = 300000,
				.bandwidth = 6,
				.datarate = 8,
				.implicit_hdr = false,
				.implicit_payload_length = 17,
				.implicit_crc_en = false,
				.implicit_coderate = 1
			},
			// FSK 
			.ifFSKConf = {
				.enable = false,
				.rf_chain = 1,
				.freq_hz = 300000,
				.bandwidth = 4,
				.datarate = 50000
			},
			.demodConf = {
				// chan_multiSF_All spreading_factor_enable bit field
				.multisf_datarate = 0xff
			}
		},
	.gateway = {
		.gatewayId = 0xaa555a0000000000,
		.serverPortUp = 1700,
		.serverPortDown = 1700,
		.keepaliveInterval = 10,
		.statInterval = 30,
		.pushTimeoutMs = {
			.tv_sec = 0,
			.tv_usec = 50000
		},
		.forwardCRCValid = true,
		.forwardCRCError = false,
		.forwardCRCDisabled = false,
		.refGeoCoordinates = {
			.lat = 0,
			.lon = 0,
			.alt = 0
		},
		.fakeGPS = false,
		.beaconPeriod = 0,
		.beaconFreqHz = 866500000,
		.beaconFreqNb = 1,
		.beaconFreqStep = 0,
		.beaconDataRate = 8,
		.beaconBandwidthHz = 125000,
		.beaconInfoDesc = 0,
		.autoQuitThreshold = 0
	},
	// Debug nb_ref_payload, count: 2
	.debug = {
		.nb_ref_payload = 2,
		.ref_payload = {
			{
				.id = 0xcafe1234
			},
			{
				.id = 0xcafe2345
			}
		},
		.log_file_name = "loragw_hal.log"
	},
	.serverAddr = "eu1.cloud.thethings.network",
	.gpsTtyPath = "/dev/ttyAMA0",
	.name = "IN-865-867",
},
{
	// kr_920_923.sx1261
		.sx1261 = {
			.sx1261 = {
				.spi_path = "",
				.rssi_offset = 0
			},
			.spectralScan = {
				.enable = false,
				.freq_hz_start = 0,
				.nb_chan = 0,
				.nb_scan = 0,
				.pace_s = 0
			},
			.lbt = {
				.enable = false,
				.nb_channel = 0
			}
		},
		.sx130x = {
			.boardConf = {
				.lorawan_public = true,
				.clksrc = 0,
				.full_duplex = false,
				.com_type = (lgw_com_type_t) 1,
				.com_path = "/dev/ttyACM0"
			},
			.antennaGain = 0,
			.tsConf = {
				.enable = false,
				.mode = (lgw_ftime_mode_t) 0
			},
			.rfConfs = {
				// Radio 0
				{
					.enable = true,
					.freq_hz = 922400000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = true,
					.single_input_mode = false
				},
				// Radio 1
				{
					.enable = true,
					.freq_hz = 923000000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = false,
					.single_input_mode = false
				}
			},
			.tx_freq_min = {
				920900000,
				0
			},
			.tx_freq_max = {
				923300000,
				0
			},
			.txLut = {
				{
					.lut = {
						// TX LUT radio 0, count: 16
						{
								.rf_power = 12,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 6
						},
						{
								.rf_power = 13,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 7
						},
						{
								.rf_power = 14,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 8
						},
						{
								.rf_power = 15,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 9
						},
						{
								.rf_power = 16,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 10
						},
						{
								.rf_power = 17,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 11
						},
						{
								.rf_power = 18,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 12
						},
						{
								.rf_power = 19,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 13
						},
						{
								.rf_power = 20,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 14
						},
						{
								.rf_power = 21,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 15
						},
						{
								.rf_power = 22,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 16
						},
						{
								.rf_power = 23,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 17
						},
						{
								.rf_power = 24,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 18
						},
						{
								.rf_power = 25,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 19
						},
						{
								.rf_power = 26,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 21
						},
						{
								.rf_power = 27,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 22
						}
					},
					.size = 16
				},
				{
					.size = 0
				}
			},
			.ifConfs = {
				{
					// chan_multiSF_0
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -300000
				},
				{
					// chan_multiSF_1
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -100000
				},
				{
					// chan_multiSF_2
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 100000
				},
				{
					// chan_multiSF_3
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 300000
				},
				{
					// chan_multiSF_4
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -100000
				},
				{
					// chan_multiSF_5
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 100000
				},
				{
					// chan_multiSF_6
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 300000
				},
				{
					// chan_multiSF_7
					.enable = false,
					.rf_chain = 1,
					.freq_hz = 300000
				}
			},
			// Lora std 
			.ifStdConf = {
				.enable = false,
				.rf_chain = 0,
				.freq_hz = 300000,
				.bandwidth = 6,
				.datarate = 8,
				.implicit_hdr = false,
				.implicit_payload_length = 17,
				.implicit_crc_en = false,
				.implicit_coderate = 1
			},
			// FSK 
			.ifFSKConf = {
				.enable = false,
				.rf_chain = 1,
				.freq_hz = 300000,
				.bandwidth = 4,
				.datarate = 50000
			},
			.demodConf = {
				// chan_multiSF_All spreading_factor_enable bit field
				.multisf_datarate = 0xff
			}
		},
	.gateway = {
		.gatewayId = 0xaa555a0000000000,
		.serverPortUp = 1700,
		.serverPortDown = 1700,
		.keepaliveInterval = 10,
		.statInterval = 30,
		.pushTimeoutMs = {
			.tv_sec = 0,
			.tv_usec = 50000
		},
		.forwardCRCValid = true,
		.forwardCRCError = false,
		.forwardCRCDisabled = false,
		.refGeoCoordinates = {
			.lat = 0,
			.lon = 0,
			.alt = 0
		},
		.fakeGPS = false,
		.beaconPeriod = 0,
		.beaconFreqHz = 923100000,
		.beaconFreqNb = 1,
		.beaconFreqStep = 0,
		.beaconDataRate = 9,
		.beaconBandwidthHz = 125000,
		.beaconInfoDesc = 0,
		.autoQuitThreshold = 0
	},
	// Debug nb_ref_payload, count: 2
	.debug = {
		.nb_ref_payload = 2,
		.ref_payload = {
			{
				.id = 0xcafe1234
			},
			{
				.id = 0xcafe2345
			}
		},
		.log_file_name = "loragw_hal.log"
	},
	.serverAddr = "nam1.cloud.thethings.network",
	.gpsTtyPath = "/dev/ttyAMA0",
	.name = "KR-920-923",
},
{
	// ru_864_870.sx1261
		.sx1261 = {
			.sx1261 = {
				.spi_path = "",
				.rssi_offset = 0
			},
			.spectralScan = {
				.enable = false,
				.freq_hz_start = 0,
				.nb_chan = 0,
				.nb_scan = 0,
				.pace_s = 0
			},
			.lbt = {
				.enable = false,
				.nb_channel = 0
			}
		},
		.sx130x = {
			.boardConf = {
				.lorawan_public = true,
				.clksrc = 0,
				.full_duplex = false,
				.com_type = (lgw_com_type_t) 1,
				.com_path = "/dev/ttyACM0"
			},
			.antennaGain = 0,
			.tsConf = {
				.enable = false,
				.mode = (lgw_ftime_mode_t) 0
			},
			.rfConfs = {
				// Radio 0
				{
					.enable = true,
					.freq_hz = 864500000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = true,
					.single_input_mode = false
				},
				// Radio 1
				{
					.enable = true,
					.freq_hz = 869000000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = false,
					.single_input_mode = false
				}
			},
			.tx_freq_min = {
				863000000,
				0
			},
			.tx_freq_max = {
				870000000,
				0
			},
			.txLut = {
				{
					.lut = {
						// TX LUT radio 0, count: 16
						{
								.rf_power = 12,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 4
						},
						{
								.rf_power = 13,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 5
						},
						{
								.rf_power = 14,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 6
						},
						{
								.rf_power = 15,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 7
						},
						{
								.rf_power = 16,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 8
						},
						{
								.rf_power = 17,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 9
						},
						{
								.rf_power = 18,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 10
						},
						{
								.rf_power = 19,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 11
						},
						{
								.rf_power = 20,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 12
						},
						{
								.rf_power = 21,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 13
						},
						{
								.rf_power = 22,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 14
						},
						{
								.rf_power = 23,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 16
						},
						{
								.rf_power = 24,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 17
						},
						{
								.rf_power = 25,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 18
						},
						{
								.rf_power = 26,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 19
						},
						{
								.rf_power = 27,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 22
						}
					},
					.size = 16
				},
				{
					.size = 0
				}
			},
			.ifConfs = {
				{
					// chan_multiSF_0
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_1
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_2
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 0
				},
				{
					// chan_multiSF_3
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 200000
				},
				{
					// chan_multiSF_4
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 400000
				},
				{
					// chan_multiSF_5
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -100000
				},
				{
					// chan_multiSF_6
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 100000
				},
				{
					// chan_multiSF_7
					.enable = false,
					.rf_chain = 1,
					.freq_hz = 300000
				}
			},
			// Lora std 
			.ifStdConf = {
				.enable = false,
				.rf_chain = 0,
				.freq_hz = 300000,
				.bandwidth = 6,
				.datarate = 8,
				.implicit_hdr = false,
				.implicit_payload_length = 17,
				.implicit_crc_en = false,
				.implicit_coderate = 1
			},
			// FSK 
			.ifFSKConf = {
				.enable = false,
				.rf_chain = 1,
				.freq_hz = 300000,
				.bandwidth = 4,
				.datarate = 50000
			},
			.demodConf = {
				// chan_multiSF_All spreading_factor_enable bit field
				.multisf_datarate = 0xff
			}
		},
	.gateway = {
		.gatewayId = 0xaa555a0000000000,
		.serverPortUp = 1700,
		.serverPortDown = 1700,
		.keepaliveInterval = 10,
		.statInterval = 30,
		.pushTimeoutMs = {
			.tv_sec = 0,
			.tv_usec = 50000
		},
		.forwardCRCValid = true,
		.forwardCRCError = false,
		.forwardCRCDisabled = false,
		.refGeoCoordinates = {
			.lat = 0,
			.lon = 0,
			.alt = 0
		},
		.fakeGPS = false,
		.beaconPeriod = 0,
		.beaconFreqHz = 869100000,
		.beaconFreqNb = 1,
		.beaconFreqStep = 0,
		.beaconDataRate = 9,
		.beaconBandwidthHz = 125000,
		.beaconInfoDesc = 0,
		.autoQuitThreshold = 0
	},
	// Debug nb_ref_payload, count: 2
	.debug = {
		.nb_ref_payload = 2,
		.ref_payload = {
			{
				.id = 0xcafe1234
			},
			{
				.id = 0xcafe2345
			}
		},
		.log_file_name = "loragw_hal.log"
	},
	.serverAddr = "eu1.cloud.thethings.network",
	.gpsTtyPath = "/dev/ttyAMA0",
	.name = "RU-864-870",
},
{
	// us_902_928.sx1261
		.sx1261 = {
			.sx1261 = {
				.spi_path = "",
				.rssi_offset = 0
			},
			.spectralScan = {
				.enable = false,
				.freq_hz_start = 0,
				.nb_chan = 0,
				.nb_scan = 0,
				.pace_s = 0
			},
			.lbt = {
				.enable = false,
				.nb_channel = 0
			}
		},
		.sx130x = {
			.boardConf = {
				.lorawan_public = true,
				.clksrc = 0,
				.full_duplex = false,
				.com_type = (lgw_com_type_t) 1,
				.com_path = "/dev/ttyACM0"
			},
			.antennaGain = 0,
			.tsConf = {
				.enable = false,
				.mode = (lgw_ftime_mode_t) 0
			},
			.rfConfs = {
				// Radio 0
				{
					.enable = true,
					.freq_hz = 904300000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = true,
					.single_input_mode = false
				},
				// Radio 1
				{
					.enable = true,
					.freq_hz = 905000000,
					.rssi_offset = -215.4,
					.rssi_tcomp = {
						.coeff_a = 0,
						.coeff_b = 0,
						.coeff_c = 20.41,
						.coeff_d = 2162.56,
						.coeff_e = 0
					},
					.type = (lgw_radio_type_t) 5,
					.tx_enable = false,
					.single_input_mode = false
				}
			},
			.tx_freq_min = {
				923000000,
				0
			},
			.tx_freq_max = {
				928000000,
				0
			},
			.txLut = {
				{
					.lut = {
						// TX LUT radio 0, count: 16
						{
								.rf_power = 12,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 6
						},
						{
								.rf_power = 13,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 7
						},
						{
								.rf_power = 14,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 8
						},
						{
								.rf_power = 15,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 9
						},
						{
								.rf_power = 16,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 10
						},
						{
								.rf_power = 17,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 11
						},
						{
								.rf_power = 18,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 12
						},
						{
								.rf_power = 19,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 13
						},
						{
								.rf_power = 20,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 14
						},
						{
								.rf_power = 21,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 15
						},
						{
								.rf_power = 22,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 16
						},
						{
								.rf_power = 23,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 17
						},
						{
								.rf_power = 24,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 18
						},
						{
								.rf_power = 25,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 19
						},
						{
								.rf_power = 26,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 21
						},
						{
								.rf_power = 27,
								.dig_gain = 0,
								.pa_gain = 1,
								.dac_gain = 0,
								.mix_gain = 5,
								.offset_i = 0,
								.offset_q = 0,
								.pwr_idx = 22
						}
					},
					.size = 16
				},
				{
					.size = 0
				}
			},
			.ifConfs = {
				{
					// chan_multiSF_0
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -400000
				},
				{
					// chan_multiSF_1
					.enable = true,
					.rf_chain = 0,
					.freq_hz = -200000
				},
				{
					// chan_multiSF_2
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 0
				},
				{
					// chan_multiSF_3
					.enable = true,
					.rf_chain = 0,
					.freq_hz = 200000
				},
				{
					// chan_multiSF_4
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -300000
				},
				{
					// chan_multiSF_5
					.enable = true,
					.rf_chain = 1,
					.freq_hz = -100000
				},
				{
					// chan_multiSF_6
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 100000
				},
				{
					// chan_multiSF_7
					.enable = true,
					.rf_chain = 1,
					.freq_hz = 300000
				}
			},
			// Lora std 
			.ifStdConf = {
				.enable = true,
				.rf_chain = 0,
				.freq_hz = 300000,
				.bandwidth = 6,
				.datarate = 8,
				.implicit_hdr = false,
				.implicit_payload_length = 17,
				.implicit_crc_en = false,
				.implicit_coderate = 1
			},
			// FSK 
			.ifFSKConf = {
				.enable = false,
				.rf_chain = 1,
				.freq_hz = 300000,
				.bandwidth = 4,
				.datarate = 50000
			},
			.demodConf = {
				// chan_multiSF_All spreading_factor_enable bit field
				.multisf_datarate = 0xff
			}
		},
	.gateway = {
		.gatewayId = 0xaa555a0000000000,
		.serverPortUp = 1700,
		.serverPortDown = 1700,
		.keepaliveInterval = 10,
		.statInterval = 30,
		.pushTimeoutMs = {
			.tv_sec = 0,
			.tv_usec = 50000
		},
		.forwardCRCValid = true,
		.forwardCRCError = false,
		.forwardCRCDisabled = false,
		.refGeoCoordinates = {
			.lat = 0,
			.lon = 0,
			.alt = 0
		},
		.fakeGPS = false,
		.beaconPeriod = 0,
		.beaconFreqHz = 923300000,
		.beaconFreqNb = 8,
		.beaconFreqStep = 600000,
		.beaconDataRate = 12,
		.beaconBandwidthHz = 500000,
		.beaconInfoDesc = 0,
		.autoQuitThreshold = 0
	},
	// Debug nb_ref_payload, count: 2
	.debug = {
		.nb_ref_payload = 2,
		.ref_payload = {
			{
				.id = 0xcafe1234
			},
			{
				.id = 0xcafe2345
			}
		},
		.log_file_name = "loragw_hal.log"
	},
	.serverAddr = "nam1.cloud.thethings.network",
	.gpsTtyPath = "/dev/ttyAMA0",
	.name = "US-902-928",
}};
